export enum EduacationLevel {
  COMPLETE_MIDDLE = 'Ensino fundamental completo',
  COMPLETE_HIGH_SCHOOL = 'Ensino médio completo',
  COMPLETE_UNDERGRADUATE_DEGREE = 'Ensino superior completo',
  COMPLETE_POSTGRADUATE_DEGREE = 'Pós-graduação completa',
  COMPLETE_SPECIALIZATION = 'Especialização completa',
  COMPLETE_MASTERS_DEGREE = 'Mestrado completo',
  COMPLETE_DOCTORATE_DEGREE = 'Doutorado completo',
  COMPLETE_PHD = 'Pós-doutorado completo',
  INCOMPLETE_MIDDLE = 'Ensino fundamental incompleto',
  INCOMPLETE_HIGH_SCHOOL = 'Ensino médio incompleto',
  INCOMPLETE_UNDERGRADUATE_DEGREE = 'Ensino superior incompleto',
  INCOMPLETE_POSTGRADUATE_DEGREE = 'Pós-graduação incompleta',
  INCOMPLETE_SPECIALIZATION = 'Especialização incompleta',
  INCOMPLETE_MASTERS_DEGREE = 'Mestrado incompleto',
  INCOMPLETE_DOCTORATE_DEGREE = 'Doutorado incompleto',
  INCOMPLETE_PHD = 'Pós-doutorado incompleto',
}
